/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author jacy
 */
public class Property extends javax.swing.JDialog {
   
    
    /**
     * Creates new form Property
     */
    private  Color color;
    private  int size;
   
    public Property(java.awt.Frame parent,String itemColorText,String itemSizeText,int maximum,int minimum ) {
        super(parent, true);
        initComponents();
        this.itemColor.setText(itemColorText);
        this.itemSize.setText(itemSizeText);
        color=null;
        size=-1;
        jSlider.setMaximum(maximum);
        jSlider.setMinimum(minimum);
        sizeTextFiled.setText("1");
        
        
       jSlider.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
               sizeTextFiled.setText(String.valueOf(jSlider.getValue()));
            }
        });
    }

    public Color getColor() {
        return color;
    }

    public int getDimension() {
        return size;
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser = new javax.swing.JColorChooser();
        jSlider = new javax.swing.JSlider();
        itemColor = new javax.swing.JLabel();
        itemSize = new javax.swing.JLabel();
        sizeTextFiled = new javax.swing.JTextField();
        modifyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(Property.class, "Property.title")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(itemColor, org.openide.util.NbBundle.getMessage(Property.class, "Property.itemColor.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(itemSize, org.openide.util.NbBundle.getMessage(Property.class, "Property.itemSize.text")); // NOI18N

        sizeTextFiled.setText(org.openide.util.NbBundle.getMessage(Property.class, "Property.sizeTextFiled.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(modifyButton, org.openide.util.NbBundle.getMessage(Property.class, "Property.modifyButton.text")); // NOI18N
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(modifyButton)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemSize)
                    .addComponent(itemColor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(sizeTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(itemColor)
                .addGap(27, 27, 27)
                .addComponent(jColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(itemSize)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(modifyButton)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
       color=jColorChooser.getColor();
       size=Integer.valueOf(sizeTextFiled.getText().trim());       
       this.dispose();
    }//GEN-LAST:event_modifyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemColor;
    private javax.swing.JLabel itemSize;
    private javax.swing.JColorChooser jColorChooser;
    private javax.swing.JSlider jSlider;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField sizeTextFiled;
    // End of variables declaration//GEN-END:variables
}
